# Generated by Django 2.0.4 on 2018-04-10 07:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUG', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FUG',
            new_name='Character',
        ),
    ]
