# Generated by Django 2.0.4 on 2018-04-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUG', '0002_auto_20180410_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='post_position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='generation',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
