# Generated by Django 2.0.4 on 2018-04-10 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FUG', '0003_auto_20180410_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='post_position',
            field=models.CharField(default='?', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='character',
            name='text',
            field=models.TextField(default='?'),
        ),
    ]
