# Generated by Django 2.0.4 on 2018-04-11 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FUG', '0007_auto_20180411_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='character',
            name='title',
            field=models.CharField(max_length=20, verbose_name='이름'),
        ),
    ]
