# Generated by Django 2.0.4 on 2018-04-12 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUG', '0008_auto_20180411_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 33, 54, 517665)),
        ),
        migrations.AlterField(
            model_name='character',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 33, 54, 517665)),
        ),
        migrations.AlterField(
            model_name='information',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 33, 54, 518142)),
        ),
        migrations.AlterField(
            model_name='information',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 33, 54, 518142)),
        ),
    ]
