# Generated by Django 2.0.4 on 2018-04-10 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noble_Family_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('information_text', models.TextField(default='?')),
                ('rival_family', models.CharField(default='?', max_length=30)),
                ('friendship_family', models.CharField(default='?', max_length=30)),
                ('sect_family', models.CharField(default='?', max_length=30)),
                ('dominate_floor', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('member_family', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('origin_family_floor', models.IntegerField(blank=True, default=None, max_length=135, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
