# Generated by Django 2.0.4 on 2018-04-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noble_Family', '0002_auto_20180411_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='noble_family_information',
            name='the_head_of_a_family',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='가주'),
        ),
    ]
