# Generated by Django 2.0.4 on 2018-04-11 04:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Noble_Family', '0003_noble_family_information_the_head_of_a_family'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noble_Family_information',
            new_name='Information',
        ),
    ]
