# Generated by Django 2.0.4 on 2018-04-11 05:24

from django.db import migrations, models
import django.utils.timezone
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Noble_Family', '0005_auto_20180411_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='information',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
