# Generated by Django 2.0.4 on 2018-04-11 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Noble_Family', '0007_information_conceal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noble_Family_Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('character_information', models.TextField(default='?')),
                ('position', models.IntegerField(choices=[(1, '파도잡이'), (2, '창지기'), (3, '낚시꾼'), (4, '등대지기'), (5, '탐색꾼')], default=1)),
                ('advanced_position', models.IntegerField(choices=[(1, '길잡이'), (2, '디펜더'), (3, '단술사'), (4, '원술사'), (5, '전술사'), (6, '주술사'), (7, '화염사'), (8, '부리미')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('tag', tagging.fields.TagField(blank=True, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': 'Character',
            },
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['created_date'], 'verbose_name_plural': 'Information'},
        ),
        migrations.AlterModelOptions(
            name='information_conceal',
            options={'verbose_name': 'Conceal Information', 'verbose_name_plural': 'Conceal Information'},
        ),
        migrations.AlterField(
            model_name='information',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(help_text='Family Name', max_length=20, verbose_name='가문'),
        ),
        migrations.AlterField(
            model_name='information_conceal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
