# Generated by Django 2.0.4 on 2018-04-11 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Noble_Family', '0008_auto_20180411_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='noble_family_character',
            name='family_name',
            field=models.IntegerField(choices=[(1, '아리에 가문'), (2, '쿤 가문'), (3, '하 가문'), (4, '투 페리 가문'), (5, '유라시아 가문'), (6, '포 비더 가문'), (7, '헨도 가문'), (8, '연 가문'), (9, '아리 가문'), (10, '로 포 비아 가문')], default=1, verbose_name='가문'),
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='advanced_position',
            field=models.IntegerField(choices=[(1, 'x'), (2, '길잡이'), (3, '디펜더'), (4, '단술사'), (5, '원술사'), (6, '전술사'), (7, '주술사'), (8, '화염사'), (9, '부리미')], default=0, verbose_name='특수 포지션'),
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='character_information',
            field=models.TextField(default='?', verbose_name='개요'),
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 11, 8, 43, 35, 443675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='position',
            field=models.IntegerField(choices=[(1, '파도잡이'), (2, '창지기'), (3, '낚시꾼'), (4, '등대지기'), (5, '탐색꾼')], default=1, verbose_name='포지션'),
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 11, 8, 43, 35, 443675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='title',
            field=models.CharField(max_length=20, verbose_name='이름'),
        ),
    ]
