# Generated by Django 2.0.4 on 2018-04-12 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Noble_Family', '0010_auto_20180411_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information_conceal',
            options={'ordering': ['created_date'], 'verbose_name': 'Conceal Information', 'verbose_name_plural': 'Conceal Information'},
        ),
        migrations.AlterModelOptions(
            name='noble_family_character',
            options={'ordering': ['created_date'], 'verbose_name': 'Character'},
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 2, 59, 9, 182722, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='detail_information',
            field=models.TextField(blank=True, default='', null=True, verbose_name='상세 내용'),
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='position',
            field=models.IntegerField(choices=[(1, '파도잡이'), (2, '창지기'), (3, '낚시꾼'), (4, '등대지기'), (5, '탐색꾼'), (6, '불명')], default=1, verbose_name='포지션'),
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 2, 59, 9, 182722, tzinfo=utc)),
        ),
    ]
