# Generated by Django 2.0.4 on 2018-04-12 03:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Noble_Family', '0013_auto_20180412_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noble_family_character',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 3, 53, 15, 944255, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 3, 53, 15, 944255, tzinfo=utc)),
        ),
    ]
