# Generated by Django 2.0.4 on 2018-04-12 04:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Noble_Family', '0014_auto_20180412_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noble_family_character',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 4, 5, 52, 837887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 4, 5, 52, 837887, tzinfo=utc)),
        ),
    ]
