# Generated by Django 2.0.4 on 2018-04-12 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Noble_Family', '0016_auto_20180412_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noble_family_character',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 7, 21, 10, 926632, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 7, 21, 10, 926632, tzinfo=utc)),
        ),
    ]
