# Generated by Django 2.0.4 on 2018-04-12 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noble_Family', '0019_auto_20180412_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 33, 54, 515659)),
        ),
        migrations.AlterField(
            model_name='information',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 33, 54, 515659)),
        ),
        migrations.AlterField(
            model_name='information_conceal',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 33, 54, 516161)),
        ),
        migrations.AlterField(
            model_name='information_conceal',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 33, 54, 516161)),
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 33, 54, 516661)),
        ),
        migrations.AlterField(
            model_name='noble_family_character',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 33, 54, 516661)),
        ),
    ]
