# Generated by Django 2.0.4 on 2018-04-12 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('not_Selected_Character', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nselected_character_information',
            old_name='detail_information',
            new_name='nSelected_Character_detail_information',
        ),
        migrations.RenameField(
            model_name='nselected_character_information',
            old_name='information_text',
            new_name='nSelected_Character_information_text',
        ),
        migrations.RenameField(
            model_name='nselected_character_information',
            old_name='name',
            new_name='nSelected_Character_name',
        ),
        migrations.RenameField(
            model_name='nselected_character_information',
            old_name='position',
            new_name='nSelected_Character_position',
        ),
        migrations.RenameField(
            model_name='nselected_character_information',
            old_name='skill',
            new_name='nSelected_Character_skill',
        ),
    ]
