# Generated by Django 2.0.4 on 2018-04-12 03:45

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('not_Selected_Character', '0002_auto_20180412_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nselected_character_information',
            options={'verbose_name_plural': 'Information'},
        ),
        migrations.AddField(
            model_name='nselected_character_information',
            name='nSelected_Character_source_url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='nselected_character_information',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nselected_character_information',
            name='nSelected_Character_information_text',
            field=models.TextField(default='?', verbose_name='정보'),
        ),
        migrations.AlterField(
            model_name='nselected_character_information',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
