# Generated by Django 2.0.4 on 2018-04-12 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('not_Selected_Character', '0005_nselected_character_information_nselected_character_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='nSelected_Character_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nSelected_Character_name', models.CharField(max_length=20, verbose_name='이름')),
                ('nSelected_Character_Class', models.IntegerField(choices=[(1, '랭커'), (2, '선별인원'), (3, '그 외')], default=1)),
                ('nSelected_Character_Rank', models.IntegerField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 4, 12, 6, 10, 23, 762906, tzinfo=utc))),
                ('published_date', models.DateTimeField(default=datetime.datetime(2018, 4, 12, 6, 10, 23, 762906, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Characters',
                'ordering': ['nSelected_Character_Rank'],
            },
        ),
        migrations.AlterModelOptions(
            name='nselected_character_information',
            options={'ordering': ['created_date'], 'verbose_name_plural': 'Characters'},
        ),
    ]
