# Generated by Django 2.0.4 on 2018-04-12 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('not_Selected_Character', '0006_auto_20180412_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nselected_character_information',
            options={'ordering': ['created_date'], 'verbose_name_plural': 'Characters Information'},
        ),
        migrations.AlterModelOptions(
            name='nselected_character_list',
            options={'ordering': ['nSelected_Character_Rank'], 'verbose_name_plural': 'Characters List'},
        ),
        migrations.AlterField(
            model_name='nselected_character_list',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 7, 21, 10, 923122, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nselected_character_list',
            name='nSelected_Character_Class',
            field=models.IntegerField(choices=[(1, '랭커'), (2, '선별인원'), (3, '그 외')], default=1, verbose_name='분류'),
        ),
        migrations.AlterField(
            model_name='nselected_character_list',
            name='nSelected_Character_Rank',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='랭킹'),
        ),
        migrations.AlterField(
            model_name='nselected_character_list',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 7, 21, 10, 923122, tzinfo=utc)),
        ),
    ]
