# Generated by Django 2.0.4 on 2018-04-12 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('not_Selected_Character', '0007_auto_20180412_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nselected_character_list',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 30, 0, 469299)),
        ),
        migrations.AlterField(
            model_name='nselected_character_list',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 16, 30, 0, 469299)),
        ),
    ]
